// const types = [
//   { id: 1, name: 'normal', color: 'bg-normal' },
//   { id: 2, name: 'fire', color: 'bg-fire' },
//   { id: 3, name: 'water', color: 'bg-water' },
//   { id: 4, name: 'grass', color: 'bg-grass' },
//   { id: 5, name: 'electric', color: 'bg-electric' },
//   { id: 6, name: 'ice', color: 'bg-ice' },
//   { id: 7, name: 'fighting', color: 'bg-fighting' },
//   { id: 8, name: 'poison', color: 'bg-poison' },
//   { id: 9, name: 'ground', color: 'bg-ground' },
//   { id: 10, name: 'flying', color: 'bg-flying' },
//   { id: 11, name: 'psychic', color: 'bg-psychic' },
//   { id: 12, name: 'bug', color: 'bg-bug' },
//   { id: 13, name: 'rock', color: 'bg-rock' },
//   { id: 14, name: 'ghost', color: 'bg-ghost' },
//   { id: 15, name: 'dark', color: 'bg-dark' },
//   { id: 16, name: 'dragon', color: 'bg-dragon' },
//   { id: 17, name: 'steel', color: 'bg-steel' },
//   { id: 18, name: 'fairy', color: 'bg-fairy' },
// ];
